### ISSUE TITLE
出现了恶性报错，重装也无法解决

### ISSUE THREAD

**Issue by MZhao-ouo** [zixing131/FakeLegionZone#1]
点“继续”仍会不断弹出，无法关闭
![image](https://user-images.githubusercontent.com/70903329/223185240-1adca8fa-6f13-4d6a-ab51-0f5614eba28d.png)

**Comment by zixing131** [comment]
应该是用的硬件检测库和你的gpu不兼容，我有空升级一下

**Comment by MZhao-ouo** [comment]
我在用的是Y9000P2022，3060的显卡。

使用文明6测试，监控信息显示了一段时间后电脑绿屏，重启再打开这个软件就一直报错了。

**Comment by zixing131** [comment]
通过测试，我发现他这个注入功能不是很稳定，可能会导致游戏崩溃等，最新版的legionzone已经不用注入功能实现fps显示了，是显示一个置顶窗口，然后通过overlay把他显示到最顶层，但是我测试中发现，有些游戏全屏后无法显示帧率，只有全屏窗口或者切出去才显示，所以这个项目估计只能做成一个只能支持全屏窗口显示帧率的了。

**Comment by zixing131** [comment]
此项目不再维护，仅作学习交流之用，联想Y9000P2022机型建议使用官方版本软件显示帧率
